# This file is part of the CampaignChain package.
#
# (c) CampaignChain, Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

campaignchain_channel_mailchimp_create:
    pattern: /channel/mailchimp/create
    defaults: { _controller: CampaignChainChannelMailChimpBundle:MailChimp:create }

campaignchain_channel_mailchimp_login:
    pattern:  /channel/mailchimp/create/login
    defaults: { _controller: CampaignChainChannelMailChimpBundle:MailChimp:login }
